openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /messages/{sender_id}:
    get:
      tags: [ Message ]
      description: Get the list of sent and drafted messages
      operationId: mib.resources.messages.get_messages
      parameters:
        - name: sender_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return list of messages
        default:
          description: An error occured during retrieving the message list

components:
  schemas:
    Message:
      required:
        - sender
      type: object
      properties:
        sender:
          type: int
          description: First name of customer
          example: 1