openapi: 3.0.1
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: '0.1'
servers:
  - url: /
paths:
  /messages/all/{sender_id}:
    get:
      summary: Retrieve sent and draft messages from a specific sender ID
      tags: [ Messages ]
      description: Get the list of sent and drafted messages
      operationId: mib.resources.messages.get_all_messages
      parameters:
        - name: sender_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return list of all messages
        default:
          description: An error occured during retrieving the message list
  /messages/received/{receiver_id}:
    get:
      summary: Retrieve all messages received by receiver ID
      tags:
        - Messages
      description: Get the list message of the receiver when the delivery date is pass 
      operationId: mib.resources.messages.get_messages_received
      parameters:
        - name: receiver_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Return list of messages
        default:
          description: An error occured during retrieving the message list
  /messages/send/{sender_id}:
    get:
      summary: Get the list of messages sent by sender ID
      tags:
        - Messages
      description: Get the list of sent messages
      operationId: mib.resources.messages.get_messages_sent
      parameters:
        - name: sender_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Return list of messages
        default:
          description: An error occured during retrieving the message list
  /messages/draft/{sender_id}:
    get:
      summary: Get the list of messages drafted by sender ID
      tags:
        - Messages
      description: Get the list of drafted messages
      operationId: mib.resources.messages.get_messages_drafted
      parameters:
        - name: sender_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Return list of messages
        default:
          description: An error occured during retrieving the message list
  /message/draft:
    post:
      summary: Save a draft message
      tags:
        - Message
      description: Create a new drafted message
      operationId: mib.resources.messages.draft_message
      requestBody:
        description: Draft message
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Draft'
      responses:
        '200':
          description: Drafted message modified
        '201':
          description: Draft message created
        '400':
          description: Wrong draft creation request
        default:
          description: An error occured during retrieving the message list
  /message:
    post:
      summary: Send a message
      tags:
        - Message
      operationId: mib.resources.messages.send
      requestBody:
        description: Create a new message with the list of receiver the content and the sender
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'     
      responses:
        201:
          description: Created
        default:
          description: Error during message sending
  /message/{message_id}:
    get:
      summary: Get a specific message by id
      tags: [ Message ]
      description: Get the list of sent and drafted messages
      operationId: mib.resources.messages.get_message_by_id
      parameters:
        - name: message_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return the message 
        default:
          description: An error occured during retrieving the message list
    delete:
      summary: Delete a specific message by id
      tags: [ Message ]
      description: Delete the message with the specify id
      operationId: mib.resources.messages.delete_message_by_id
      parameters:
        - name: message_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Message as been delete
        default:
          description: An error occured during delete the message
    
components:
  schemas:
    Message:
      required:
        - sender
        - content
      type: object
      properties:
        sender:
          type: integer
          description: Id of the message's sender
          example: 1
        date_of_delivery:
          type: string
          description: Date when the message will be sent
          example: '2022-01-01'
        time_of_delivery:
          type: string
          description: Time when the message will be sent
          example: '10:21'
        content:
          type: string
          description: Text of the message
          example: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC'
        title:
          type: string
          description: Message title
          example: 'New Message to you'
        bad_content:
          type: boolean
          description: Customer phone number
          example: False
        number_bad:
          type: integer
          description: Number of bad word in the message
          example: 0
        font:
          type: string
          description: Description of the font of the message
          example: 'Arial'
        is_draft:
          type: boolean
          description: Describe is the message is finish or not
          example: False
        receivers:
          type: array
          items:
            type: integer
          description: List of users who will receive the message
          example: [2,1]
    Draft:
      required:
        - sender
      type: object
      properties:
        sender:
          type: integer
          description: Id of the message's sender
          example: 1
        date_of_delivery:
          type: string
          description: Date when the message will be sent
          example: '12/01/2022'
        time_of_delivery:
          type: string
          description: Time when the message will be sent
          example: '10:21'
        content:
          type: string
          description: Text of the message
          example: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC'
        title:
          type: string
          description: Message title
          example: 'New Message to you'
        bad_content:
          type: boolean
          description: Detect bad content in the message
          example: False
        number_bad:
          type: integer
          description: Number of bad word in the message
          example: 0
        font:
          type: string
          description: Description of the font of the message
          example: 'Arial'
        is_draft:
          type: boolean
          description: Describe is the message is finish or not
          example: True
        receivers:
          type: array
          items:
            type: integer
          description: List of users who will receive the message
          example: [2,1]