openapi: 3.0.1
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: '0.1'
servers:
  - url: /
paths:
  /messages/all/{sender_id}:
    get:
      summary: Retrieve sent and draft messages from a specific sender ID
      tags: [ Messages ]
      description: Get the list of sent and drafted messages
      operationId: mib.resources.messages.get_all_messages
      parameters:
        - name: sender_id
          description: User unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return list of all messages
        default:
          description: An error occured during retrieving the message list
  /messages/received/:
    post:
      summary: Retrieve all messages received by a receiver
      tags:
        - Messages
      description: Get the list message of the receiver when the delivery date is pass 
      operationId: mib.resources.messages.get_messages_received
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                receiver: 
                  type: string
                  description: Id of the user
                  example: "1"
                date:
                  type: string
                  description: datetime
                  example: '2022-01-01 10:00'
                filter:
                  type: boolean
                  description: tells if the filter is active
                  example: false
      responses:
        '200':
          description: Return list of messages
        default:
          description: An error occured during retrieving the message list
  /message/list/{msg_id}/{receiver_id}:
    get:
      summary: Retrieve the message list of a receiver
      tags: [ Message List ]
      operationId: mib.resources.messages.get_msglist_by_id
      parameters:
        - name: msg_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: receiver_id
          description: Receiver unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return list of all messages
        default:
          description: An error occured during retrieving the message list
    delete:
      summary: delete a receiver in message list
      tags:
        - Message List
      operationId: mib.resources.messages.delete_receiver
      parameters:
        - name: msg_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: receiver_id
          description: Receiver unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Receiver deleted
        default:
          description: An error occured during retrieving the message list

  /message/draft:
    post:
      summary: Save a draft message
      tags:
        - Message
      description: Create a new drafted message
      operationId: mib.resources.messages.draft_message
      requestBody:
        description: Draft message
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: Drafted message modified
        '201':
          description: Draft message created
        '400':
          description: Wrong draft creation request
        default:
          description: An error occured during retrieving the message list
  /message/send:
    post:
      summary: Send a message
      tags:
        - Message
      operationId: mib.resources.messages.send
      requestBody:
        description: Create a new message with the list of receiver the content and the sender
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'    
      responses:
        201:
          description: Created
        default:
          description: Error during message sending
  /message/{message_id}:
    get:
      summary: Get a specific message by id
      tags: [ Message ]
      description: Get the list of sent and drafted messages
      operationId: mib.resources.messages.get_message_by_id
      parameters:
        - name: message_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return the message 
        default:
          description: An error occured during retrieving the message list
    delete:
      summary: Delete a specific message by id
      tags: [ Message ]
      description: Delete the message with the specify id
      operationId: mib.resources.messages.delete_message_by_id
      parameters:
        - name: message_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Message as been delete
        404:
          description: Message not found
        default:
          description: An error occured during delete the message
  /message/{message_id}/images:
    get:
      summary: Get the list of images associated to the message
      tags:
        - Images
      description: Get the list of images in the message
      operationId: mib.resources.messages.retrieve_message_images
      parameters:
        - name: message_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Return list of images
        default:
          description: An error occured during retrieving the message list
  /notify/{msg_list_id}:
    post:
      summary: Notify the read of a message
      tags:
        - Message
      operationId: mib.resources.messages.notify_read
      parameters:
        - name: msg_list_id
          description: Message list unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Read set correctly
        400:
          description: The message is already inside
  /message/forward/{user_id}:
    post:
      summary: Forward a message
      tags:
        - Message
      operationId: mib.resources.messages.forward
      parameters:
        - name: user_id
          description: Message unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Insert inside the message list the other ids for the forward
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forward'    
      responses:
        200:
          description: Created
        400:
          description: The message is already inside

components:
  schemas:
    Forward:
      required:
        - destinators
        - messageid
      type: object
      properties:
        destinators:
          type: array
          items:
              type: integer
              description: List of users who will receive the message
          example: [2,1]
        messageid:
          type: string
          description: Id of the message
          example: '0'

    Message:
      required:
        - sender
      type: object
      properties:
        payload:
          type: object
          properties:
            title:
              type: string
              description: Message title
              example: 'New Message to you'
            content:
              type: string
              description: Text of the message
              example: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC'
            date_of_delivery:
              type: string
              description: Date when the message will be sent
              example: '2022-01-01'
            time_of_delivery:
              type: string
              description: Time when the message will be sent
              example: '10:21'
            font:
              type: string
              description: Description of the font of the message
              example: 'Arial'
            destinator:
              type: array
              items:
                type: integer
              description: List of users who will receive the message
              example: [2,1]
        sender:
          type: integer
          description: Id of the message's sender
          example: 1
        message_id:
          type: integer
          description: Id of the message
          example: 0
        delete_image_ids:
          type: array
          items:
            type: integer
          description: List of users who will receive the message
          example: []
        delete_user_ids:
          type: array
          items:
            type: integer
          description: List of users who will receive the message
          example: []
        raw_images:
          type: array
          items:
            type: string
          description: List of images
          example: []
        mimetypes:
          type: array
          items:
            type: string
          description: List of mimetypes
          example: []