"""empty message

Revision ID: 1920d94ee207
Revises: 
Create Date: 2021-12-01 17:38:01.718354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1920d94ee207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('date_of_delivery', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('bad_content', sa.Boolean(), nullable=True),
    sa.Column('number_bad', sa.Integer(), nullable=True),
    sa.Column('font', sa.Unicode(length=128), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['message'], ['Message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msglist',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('hasReported', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['msg_id'], ['Message.id'], ),
    sa.PrimaryKeyConstraint('msg_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msglist')
    op.drop_table('image')
    op.drop_table('Message')
    # ### end Alembic commands ###
